### ISSUE TITLE
Training Data for TinyBERT

### ISSUE THREAD

**Issue by fraboeni** [prajjwal1/generalize_lm_nli#36]
Hi @prajjwal1,

Thank you very much for this great repo and work.
I would be interested in working with your bert-tiny model. 

For this work, it would be of importance to know what data exactly this model was obtained from. I could not find a concrete pointer.
Would you be able to guide me to a specification of this information?

Thank you a lot in advance and kind regards!

**Comment by prajjwal1** [comment]
All these models were trained in the same way as BERT was trained on. This means they were trained on the same data BERT was trained on. BERT paper would have more details.

**Comment by fraboeni** [comment]
Thank you very much!
